Milestone 2: User interface
dansantander/tictactoe pull request #2
Opened 2020-03-20 17:41 UTC by dansantander

This Milestone complies with the following requirements: 

Think about steps needed to play the game:
what do you need from player?
what do you need to display for player?

Display prompts for users, collect user input and only mock the basic flow of the game.

Make sure that you can run your game with your executable file and play with the basic flow.

The final point of this milestone is to make sure that you thought about all actions needed to play Tic Tac Toe. **It does not need to work yet** - this will be done in the next milestone.

2020-03-20 20:37 UTC, pelzolga123 requested changes
Project requires changes.

2020-03-20 20:40 UTC, pelzolga123 commented
## Hi Team! ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
###  Good job so far :+1: 
In this milestone not everything must work, the point is to make sure you thought about everything. Points listed below are missing:
 
* [ ] Game should ask player to select from available moves.
* [ ] Game should inform player if selected move is invalid.
* [ ] Game should display board after player move.

### Please kindly fix the above issues and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

2020-03-21 02:27 UTC, suretrust requested changes
Hi team, 👋 

### Great job thus far. 🙌 Please see my comments. 👇 

- [ ] Your code could not run. It was complaining about the `green` method. Then I tried to remove it, I got the error below again:

```ruby
bin/main.rb:79:in `<main>': uninitialized constant Player (NameError)
```

**Please ensure to submit a code that runs properly. This will enable the reviewer to review your code and check if you have implemented the first reviewer's suggestions.** Kindly submit for another code review request once this has been fixed.  _Happy coding!_ 🎉

2020-03-21 02:27 UTC, suretrust commented on bin/main.rb
> +public
This doesn't need to be defined explicitly, ruby already knows.

2020-03-21 02:27 UTC, suretrust commented on bin/main.rb
> +X = 'X'.green
When I tried running your code, I got the error below:
```ruby
bin/main.rb:78:in `<main>': undefined method `green' for "X":String (NoMethodError)
```
<img width="1190" alt="Screenshot 2020-03-21 at 03 22 00" src="https://user-images.githubusercontent.com/31304943/77217487-40002480-6b23-11ea-9cb6-fdb32568b8dd.png">

2020-03-21 17:36 UTC, suretrust approved these changes
Hi team, 👋 

### Great job implementing the suggested changes. 🙌 Let's get this merged! 👍 

_Good luck with your future milestones and happy coding!_ 🎉

2020-03-22 15:44 UTC, merged